export type Company = {
    id?: string,
    company: string,
    city?: string,
    contact?: string,
    phone?: string,
    defbranch?: string,
    hardware: boolean,
    hrdwexpiry?: Date,
    software: boolean,
    sftwexpiry?: Date,
    rmactive: boolean,
    rmacexpiry?: Date,
    cod?: boolean,
    codreason?: string,
    subscript?: boolean,
}

export type Ticket = {
    serviceid?: string,
    company: string,
    product?: string,
    model?: string,
    serialnum?: string,
    daterec?: Date,
    darecomp?: Date,
    cod?: boolean,
    priority?: boolean,
    completed?: boolean,
    tech?: string,
    calltype?: string,
    branch?: string,
    problem?: string,
    solution?: string,
    software?: boolean,
    hardware?: boolean,
    rmmonitor?: boolean,
    minutes?: number,
}

export type CompanyTicket = Company & Ticket;