export type SearchMap = Record<string, string>

export const defaultSearch: SearchMap = {
    "376 LIQUOR": "376 Liquor -",
    "AHTAHKAKOOP GENERAL STORE": "Ahtahkakoop General Store",
    "ANN'S C-STORE": "Ann's C Store",
    "ANTHOLOGY HOME COLLECTION": "Anthology",
    "ASQUITH HOTEL": "Asquith Hotel",
    "ATHABASCA LAKESIDE CAFE": "Athabasca Lakeside Cafe - Cash",
    "BALDUR TRADING": "Baldur ",
    "BB LIQUOR & VARIETY": "BBLiquor",
    "BIRCHWOOD GROCERY": "Birchwood",
    "BIRD'S CONF-SOUTHEND": "Bird's Conf Southend",
    "BLACK LAKE VENTURES": "Black Lake Ventures - Cash 1 (Server)",
    "BLAINE LAKE HARDWARE": "Blaine Lake Hardware - Cash",
    "BROKEN ARROW JUNCTION": "!trading+Broken Arrow ",
    "BROKEN ARROW TRADING POST": "Broken Arrow Trading Post",
    "BRYSON ENTERPRISES": "Bryson Enterprises -",
    "BRYX LIQUOR": "Bryx",
    "CALLING RIVER (OCHAPOWACE)": "Calling River -",
    "CATHEDRAL SOCIAL SASKATOON": "Cathedral Social",
    "CHURCHILL RIVER TRADING POST": "Churchill River Trading Post -",
    "CLEARWATER RIVER GAS": "Clearwater River -",
    "CREE LAND MINI MART": "Creeland",
    "CUPPA'T": "Cuppa Tea",
    "M & S CONVENIENCE STORE": "m+&+S+Conv",
    "D'S CONVENIENCE": "D's Convenience -",
    "DINSMORE AUTO CARE 1": "Dinsmore Auto +Care",
    "EAGLES LAKE GAS BAR": "Eagle's Lake Gas",
    "EILEEN BRUNO": "+eileen+bruno",
    "ENGLISH RIVER - BEAUVAL": "English River Beauval",
    "ENGLISH RIVER - GRASSWOODS": "English River Grasswood",
    "ENGLISH RIVER - PATUNAK": "English River Patu",
    "ETHELBERT SERVICE CENTRE": "Ethelbert Service",
    "EVERGREEN CENTRE": "Evergreen -RM",
    "FIRESIDE BISTRO": "Fireside Bistro - RM",
    "FISHING LAKE CONVENIENCE STORE": "Fishing Lake",
    "FUDDRUCKERS REGINA": "Fuddruckers",
    "GILLYBEANS CAFE": "Gillybeans Cafe",
    "GLENTWORTH COUNTRY STORE": "Glentworth Country",
    "GOLD EAGLE GAS BAR": "GOLD EAGLE GAS BAR -",
    "GRANDMOTHERS BAY STO": "Grandmother's Bay Store",
    "GRASSLANDS INN": "Grassland",
    "HARVARD WESTERN - YELLOWGRASS": "!rouleau+!roleau+Harvard Western Ins -",
    "HUES ART SUPPLY": "Hues Art Supply - ",
    "INDUSTRIAL PARK CAFE": "Industrial Cafe",
    "KAHKEWISTAHAW STORE": "Kahkewistahaw (YRK) ",
    "KAWACATOOSE GENERAL STORE": "Kawacatoose BO",
    "KEESEEKOOSE GAS BAR": "Keeseekoose -",
    "KEETHANOW FOOD SUPERMARKET": "KGC - Supermarket",
    "KEETHANOW GAS BAR": "KGC - Keethanow Gas Bar Server",
    "KING'S DEPARTMENT STORE": "King's Department Store -",
    "KORNER GAS": "Korner Gas - Cash",
    "LAWSON AUTO SPA": "LAWSON AUTO SPA",
    "LE MACARON DECADENT DESSERTS INC": "Le Macaron",
    "LIONEL HEAD MEMORIAL STORE": "Lionel Head Mem -",
    "LIQUOR SPOT 1ST AVE": "Liquor Spot 2",
    "LITTLE RED RIVER GAS & TIRE INC.": "Little Red River -",
    "LUMSDEN HOTEL": "Lumsden Hotel RM",
    "MAN & GIRL": "Man & Girls -",
    "MAVERICK AND CO LIQUOR": "Maverick and Co. -",
    "MIDALE QUICK STOP": "Midale Quick Stop",
    "MORIN LAKE MARKET": "Morin Lake Market",
    "MUSCOWPETUNG STOP & GO": "Muscowpetung -",
    "MUSKEG LAKE CREE NATION": "Muskeg Lake (MLCN) -",
    "MUSKODAY STORE AND GAS BAR": "Muskoday Gas -",
    "MUSKOWEKWAN GAS BAR": "Muskowekwan",
    "NAKOTA JUNCTION": "Nakota",
    "NORTH PORTAL DUTY FR": "North Portal ",
    "OLY'S TRADING POST": "Oly's Trading Post",
    "P&M GAS BAR": "P & M Gas Bar - Cash 1 Server",
    "PASKWA PIT STOP": "Paskwa ",
    "RIVERBEND GAS & CON (AHTAHKAKOOP)": "Riverbend",
    "RIVERSIDE GAS BAR": "Riverside",
    "ROBINS CORNER ENTERPRISE": "Robins Corner Enterprise",
    "SAULTEAUX CROSSING": "Saulteaux Crossing",
    "SEDLEY COUNTRY CONVE": "Sedley",
    "SIKUP GENERAL STORE": "Sikup",
    "SMAK YORKTON": "SMAK Yorkton -",
    "SPENCER FINE FOODS": "Spencer's",
    "STANLEY MISSION GAS BAR": "Stanley Mission",
    "T JUNCTION GAS": "T Junction",
    "TANTALLON CO-OP": "Tantallon CO-OP",
    "THE BEAR CAVE CONFECTIONERY": "The Bear Cave Confectionery",
    "THE LIQUOR SPOT": "!2 +Liquor Spot",
    "THE SWEET SPOT": "!Edmonton+Sweet Spot",
    "THE TEACHER'S TRUNK": "Teacher's Trunk -",
    "THE TRAPPERS CABIN": "The Trapper's Cabin - Cash",
    "THIS N THAT RAYMORE": "This n' That - Cash 1",
    "THREE NATIONS GAS BAR": "Three Nations",
    "URSA CANNABIS": "Ursa Cannabis",
    "WAPASKOKIMAW GAS BAR": "+Wapaskokimaw",
    "WATERHEN LAKE GENERAL STORE": "Waterhen Lake General Store -",
    "3 HALL PUBLIC HOUSE": "3 Hall Public House -",
    "AMIGOS CANTINA": "AMIGO'S - RM",
    BIRMINGHAMS: "Birminghams",
    "BIRMINGHAMS REGINA": "Birmingham's Regina",
    BUSHWAKKER: "Bushwakker",
    "CABEZA GRANDE - COCHRANE": "Cabeza Cochrane - RMServer",
    "CAFE FRANCAIS": "Cafe Francais RM1 Server",
    "CAROLINE'S RESTAURANT": "Caroline's Restaurant - RM1 Server",
    "CHICKEN TENDEES": "Chicken Tendees - Vel",
    "CHIEF'S ISLAND STORE": "Chief Island -",
    "CHOPPER K STEAKHOUSE": "Chopper K RM1",
    "CHRIS' PLACE": "CHRIS'S PLACE - RM1 *new*",
    "CITY CENTRE BINGO": "City Center Bingo - B/O",
    "CJ MARKET": "CJ Market-Cash1",
    COCKTAIL: "Cocktail - RM",
    "COLONIAL COLD BEER & WINE STORE": "Colonial Offsale -",
    "COMMERCIAL CAR & TRUCK WASH": "Comm Truck",
    "CONEY ISLAND CAFE (DEWEDNEY)": "Coney Island",
    "COOKE INSURANCE": "+cooke+insurance",
    "COUNTRY SQUIRE": "Country Squire RM",
    "COWESSES GAS II": "Cowesess II Server",
    "CRAVINGS & STATS": "cravings|stats",
    "CREE LAND MINI-MART II": "Cree Land Mini",
    "CREE WAY GAS LTD.": "CreeWay East -",
    "CROSS COUNTRY FOODS": "Cross Country",
    "CROSSROADS INN": "Crossroads Inn",
    "CROWE'S NEST GAS BAR": "Crowes Nest",
    "CRYSTAL SPRINGS CONVENIENCE": "CRYSTAL",
    "DARCY ACRES FEED & SUPPLY": "Darcy Acre",
    "DAYS INN - ESTEVAN": "Days I",
    "DJ'S GAS BAR": "DJ's",
    "DM'S KORNER STATION": "DM Korner Station",
    "DODGIE'S CONVENIENCE STORE 2006": "DODGIES",
    "ENGLISH RIVER - THE PATCH": "The Patch",
    "F.H. WIGMORE (FIVE HILLS)": "FH Wigmore - RM1 Server",
    "FANCY FORK": "Fancy Fork RM",
    "FILCANASIAN ENTERPRISES": "FilCanAsian Cash1",
    "FIRE CREEK GAS & GRILL": "FireCreek -",
    "FLAVOURS OF INDIA": "Flavours of India",
    "FLYING DUST FUEL": "Flying Dust -",
    "FOX & HOUNDS": "Fox",
    "GAS PLUS - MCKERCHER": "Lakeview Gas Plus -",
    "GET IT ON THE WAY": "Get it on",
    "GIENI'S FINE FAMILY FOODS": "Gieni's - RM",
    "GIENI'S FINE FAMILY REST. CR": "GIENI'S CARROT RIVER -",
    "GLASLYN MOTEL": "Glaslyn Motel",
    "GOLAR SALES & SERVICE": "Golar Sales",
    "GOLF'S STEAK HOUSE": "Golf's",
    "GOOD HABITS MARKET INC": "Good Habits",
    "GOOSE LAKE GAS & GROCERY": "Goose Lake",
    "GOULD BILLIARD & PATIO": "Gould Billiard & Patio Cash1",
    "GRAINFIELDS - CIRCLE": "Grainfields-Circle",
    "GRAINFIELDS - PA": "!circle+Grainfields",
    "GRANDVIEW BEACH STOR": "GrandView Service (United Petroleum J&D)",
    "GRANT HALL INN": "Grant Hall",
    "GREEN ACRES GREENHOUSE": "+green acres green+house",
    "GREEN LAKE GAS & GROCERY": "Green Lake Gas and Grocery - Cash 1",
    "GREEN LEAF KITCHEN": "Green Leaf Kitchen RMServer",
    "GREEN SUPERMARKET": "Green Supermarket",
    "GREG'S GROCERY PLUS": "Greg's Cash",
    "HAFFORD FINE FOODS": "Hafford Fine Foods -",
    "HARVARD WESTERN - ROLEAU": "!(yellowgrass)+Harvard Western Ins -",
    "HEARTLAND MOTOR INN": "Heartland",
    "HERBS & HEALTH": "Herbs",
    "HIGHLAND CURLING CLU": "Highland Curling Club RM Server",
    "HIGHLINE CAFE & LOUNGE": "Highline Cafe Server",
    "HIGHWAY CONVENIENCE": "Highways (Pelican Narrows) -",
    "HOFF INSURANCE": "Hoff Backoffice PC",
    "HOMESTYLE FLOORS & INTERIOR": "Homestyle",
    "HOP & VINE": "Hop & Vine RM",
    "IANNONE'S FOOTWEAR": "Iannone",
    "IMPERIAL CO-OP": "Imperial Coop",
    "INDIA MARKET REGINA": "India Market Cash 1",
    "ISLAND LAKE FIRST NATION STORE": "Island Lake (Ministikw",
    "JACK'S STORE": "Jack's Store",
    "JANS BAY CONVENIENCE": "Jans Bay Convenience",
    "JNJ'S GENERAL STORE": "JNJ",
    "JOHNNY'S BISTRO": "Johnny's Bistro - RM",
    "KAHKEWISTAHAW GAS (SKTN)": "Kahkewistahaw (SKT)",
    "KANATINAK STORE(POUNDMAKER)": "Kanatinak",
    "KENOSEE MINI MART": "Kenosee MM",
    "KERROBERT REDDI MART": "Kerrobert Reddi Mart",
    "KI'YA'NAW GAS BAR": "+Ki +Ya +Naw",
    "KING ARTHUR'S FINE FOODS": "Super Fast Grocery (Climax)",
    "KLEIN'S BROAD STREET": "Klein's Food Mart",
    "LAKESIDE GRILL (KAHKEWISTAHAW)": "Lakeside Grill Vel",
    "LITTLE PINE PETRO CAN": "Little Pine (Reserve) -",
    "MDEEZ CONF & GAS BAR": "MDeez",
    "MIAMI GAS BAR": "Miami Gas Bar",
    "MIAMI SNACK SHACK": "@Miami Snack Shack - RM1",
    "MICHAEL'S COFFEE SHOP - WEYBURN": "!estevan+Michael's Coffee Shop",
    "MICHAEL'S COFFEE SHOP ESTEVAN": "Michael's Coffee Shop Estevan RM1",
    "MIKEL COFFEE": "Mikkel Coffee - Downtown",
    "MIRCH MASALA - 22ND ST": "Mirch - 22ND Street",
    "MIRCH MASALA & INDIAN SWEET CUISINE": "Mirch Central - RM1",
    "MOM'S NUTRITION CENT": "MOM'S NUTRITIONAL CENTER - B/O *NEW*",
    "MONT NEBO STORE (AHTAHKAKOOP)": "Mont Nebo",
    "MOOSE JAW CO-OP": "Moose Jaw Co",
    "MOUNTAINVIEW FOOD & FUEL STORE": "Mountainview -",
    "NICKY'S CAFE": "Nicky's Cafe EP RMServer",
    "NORQUAY GAS & CARWASH": "Norquay Grocery",
    "NORTH PRO SPORTS LP (MLCN)": "northpro|North +pro",
    "NORTHEAST SERVICE": "North East Service",
    "OCHAPOWACE COMMUNITY": "Ochapowace",
    "OCTOBER MODERN ASIAN RESTAURANT": "October Modern Asian Rest. - RM1",
    "PARK HOTEL(1992) LTD": "Park Hotel",
    "PATINA FLOOR & DECOR": "Patina Floor & Decor - CASH1",
    "PBCN P.A. FUEL -2ND AVE": "PBCN 2nd Ave -",
    "PBCN P.A. FUEL (22ND ST E)": "PBCN 22n",
    "PBCN P.A. FUEL (CREIGHTON)": "PBCN Creighton -",
    "PELICAN LAKE MALL C-STORE": "Pelican Lake",
    "PIERCELAND HARDWARE": "Pierceland General Supplies - Cash1*",
    "PILOT BUTTE DOMO": "Pilot Butte",
    "PRAIRIE AQUATICS & EXOTICS": "Prairie Aquatics",
    "PRONTO- KRAMER BLVD": "Pronto RMServer",
    "PROVIDENCE PL CAFETERIA": "Providence RMServer Cafe",
    "R-BAR & RESTAURANT": "R-Bar Restaurant - RM1 Server",
    "REDBERRY PHARMACY": "Redberry Pharmacy-Cash1",
    "REDS LIQUOR STORE & BEER INC": "Reds Liquor",
    "RIVERVIEW COLLEGIATE": "Riverview College (Prairie South)",
    "RODDY'S STORE": "Roddy's",
    "SABADOS INDUSTRIES": "Sabados Ind",
    "SAM'S GAS & GROCERY": "Sam+gas",
    "SANDY BAY GENERAL STORE": "SandyBay Grocery -",
    "SANDY RIDGE GAS & GR": "Sandy Ridge -",
    "SASKATOON SPCA": "SASKATOON SPCA",
    "SHOP N STAY GROCERY": "Shop+stay",
    "SIEBEN'S MEATS": "Sieben's Meats",
    "SILTON GENERAL STORE": "Silton General Store",
    "SILVERWOLF TRADING POST": "Silver Wolf Trading Post - Cash",
    "SILVERWOOD CONVENIENCE": "Silverwood Conv - Cash 1",
    "SKYE CAFE & BISTRO": "Skye Cafe RM",
    "SMITTYS - MOOSE JAW": "Smitty",
    "SNACK SHACK": "!miami+Snack+Shack",
    "SOMEWHERE ELSE PUB": "Somewhere Else#1",
    "SOUTHSHORE GOLF CLUB": "Southshore",
    "SOUTHWEST AG & AUTO": "Southwest Ag & Auto",
    "SPECKLEBELLY'S": "Specklebelly's -",
    "ST. WALBURG INN": "St. Walburg Inn -",
    "ST.WALBURG LIQUOR INN STORE": "St. Walburg Liquor",
    "STATION ARTS CENTRE": "Station Arts Center - Cash1",
    "STEPH'S PLACE": "Steph's Place - Silver 1",
    "STONE'S THROW COFFEE SHOP": "Stone's Throw",
    "STOP & GO CONFECTION": "Stop n",
    "STURGEON LAKE STORE & GAS BAR": "Sturgeon Lake ",
    "SWEET KORNER": "Sweet Korner RMServer",
    "TAPPS BREWING CO": "Tapps RMServer",
    TEPPANYAKI: "Teppanyaki - RM",
    "THE CRUSHED CAN SPORTS BAR & NIGHT": "Crushed Can - RMServer",
    "THE DAM SMOKEHOUSE": "The Dam Smokehouse RM1",
    "THE DIPLOMAT": "+diplomat+-",
    "THE EXCHANGE": "Exchange",
    "THE LIQUOR STORE ROSE": "The Liquor Store+rosetown",
    "THE LIQUOR STORE WYN": "The Liquor Store Wynyard",
    "THE SWEET SPOT (EDM)": "The Sweet Spot BO- Edmonton",
    "THIRSTY DOGZ LIQUOR": "Thirsty Dogz",
    "THIRSTY SCOLLAR": "Thirsty Scholar-RMSERVER",
    "TIPI FUEL & CONVENIENCE": "Tipi Fuel",
    "TOWN & COUNTRY GROCERY": "Town & Country",
    "TRAYA'S DINER": "@Traya's Diner (Big Bear) -RM 1 Server",
    "UNIQUE NURSERY": "Unique Nursery Cash1",
    "VALLEY GATE GAS & CONVENIENCE (R&R)": "Valley",
    "VIBANK CASH STORE": "Vibank",
    "VIETNAMESE ROLL REST.": "Vietnamese Roll Rest. - RM1",
    "VIMRIDGE WATER TREAT": "Vimridge Cash1",
    "VIVID INK STUDIO": "Vivid Ink Studio (COD)",
    "WALDHEIM FINE FOODS": "Waldheim Fine Foods",
    "WASABI - SOUTH ALBERT": "Wasabi South RMServer",
    "WESTSIDE CONFECTIONARY": "Westside Confectionary Cash",
    "WESTWIND MOTOR INN": "Westwind Motors",
    "WHITE BEAR LAKE RESORT": "White Bear Lake Resort",
    "WHITESAND REGIONAL PARK": "Whitesand Regional Park Cash 1",
    "WHO-OO CALLS": "Domo Quapelle",
    "WOLF'S STORE": "Wolf's",
    "AHTAHKAKOOP CAR WAS LTD.": "+Ahtahkakoop Car Was",
    "4 CLAW RETAIL (GORDON)": "4 Claw Retail (Gordon)",
    "FOUR POINTS COLD BEER & WINE": "4 Points (Rogers Pub)",
    "FOUR SEAS RESTAURANT": "4 Seasons",
    "ALPINE CONVENIENCE": "Alpine Convenience",
    "ATHABASCA CATERING": "Athabasca Catering",
    "AVALON COLD BEER & WINE": "Avalon Cold Beer & Wine -",
    "ED BENOANIE ENT(HATCHET LAKE)": "Benoanie Ent",
    "BIG ISLAND LAKE CREE NATION": "Big Island Lake -",
    "BLUEZ ON 2ND LIQUOR STORE": "Bluez - Cash 1",
    "BOWNESS HEALTH FOOD": "Bownes Health BO",
    "BREWED AWAKENING HILL": "Brewed Awakening",
    "BROTHERS HALAL MEAT & GROCERY": "Brothers Halal Meat & Grocery - Cash 1 *NEW*",
    "BRUCE'S LANDSCAPING": "Bruce Lansdscaping",
}

